In [79]:
import numpy as np

Assignment 5
===

In [211]:
n = 11
final = n*n
rows = n - 1
cols = n - 1
A = np.zeros((n,n))

In [212]:
print(A)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [213]:
horizontal = 0
vertical = 0
if n%2 == 1:
    axis = 2
else:
    axis = 0

while(horizontal <= rows and veritcal <= cols):
    if axis == 0:
        for i in range(vertical, cols+1):
            A[horizontal][i] = final
            final -= 1
        horizontal += 1
        axis = 1

    elif axis == 1:
        for i in range(horizontal,rows+1):
            A[i][cols] = final
            final -= 1
        cols -=1 
        axis = 2
            
    elif axis == 2:
        for i in range(cols,vertical-1,-1):
            A[rows][i] = final
            final -= 1
        rows -=1
        axis = 3
            
    elif axis == 3:
        for i in range(rows,horizontal-1,-1):
            A[i][vertical] = final
            final -= 1
        vertical +=1
        axis = 0

In [214]:
print(A)

[[101. 100.  99.  98.  97.  96.  95.  94.  93.  92.  91.]
 [102.  65.  64.  63.  62.  61.  60.  59.  58.  57.  90.]
 [103.  66.  37.  36.  35.  34.  33.  32.  31.  56.  89.]
 [104.  67.  38.  17.  16.  15.  14.  13.  30.  55.  88.]
 [105.  68.  39.  18.   5.   4.   3.  12.  29.  54.  87.]
 [106.  69.  40.  19.   6.   1.   2.  11.  28.  53.  86.]
 [107.  70.  41.  20.   7.   8.   9.  10.  27.  52.  85.]
 [108.  71.  42.  21.  22.  23.  24.  25.  26.  51.  84.]
 [109.  72.  43.  44.  45.  46.  47.  48.  49.  50.  83.]
 [110.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.]
 [111. 112. 113. 114. 115. 116. 117. 118. 119. 120. 121.]]


In [215]:
print(np.linalg.det(A))

-71066912716800.39


In [216]:
col_sum = np.zeros(n)
row_sum = np.zeros(n)

for i in range(n):
    for j in range(n):
        col_sum[i] += A[j][i]
        row_sum[i] += A[i][j]
print(col_sum)
print(row_sum)

[1166.  833.  630.  525.  486.  481.  482.  501.  570.  721.  986.]
[1056.  741.  552.  457.  424.  421.  436.  497.  636.  885. 1276.]
