Assignment 2
---

In [2]:
import numpy as np

Checking 2x2 cases

In [3]:
s = (2,2)

In [15]:
A = np.zeros(s)
A[0][0] = 1
A[0][1] = 1
det = np.linalg.det(A) 
print(A)
print(det)

[[1. 1.]
 [0. 0.]]
0.0


In [16]:
A = np.zeros(s)
A[0][0] = 1
A[1][0] = 1
det = np.linalg.det(A) 
print(A)
print(det)

[[1. 0.]
 [1. 0.]]
0.0


In [17]:
A = np.zeros(s)
A[0][0] = 1
A[1][1] = 1
det = np.linalg.det(A) 
print(A)
print(det)

[[1. 0.]
 [0. 1.]]
1.0


In [18]:
A = np.zeros(s)
A[1][0] = 1
A[0][1] = 1
det = np.linalg.det(A) 
print(A)
print(det)

[[0. 1.]
 [1. 0.]]
-1.0


In [19]:
A = np.zeros(s)
A[1][1] = 1
A[0][1] = 1
det = np.linalg.det(A) 
print(A)
print(det)

[[0. 1.]
 [0. 1.]]
0.0


In [20]:
A = np.zeros(s)
A[1][0] = 1
A[1][1] = 1
det = np.linalg.det(A) 
print(A)
print(det)

[[0. 0.]
 [1. 1.]]
0.0


Checking 2x2 determinants for all matrices only using 0's and 1's.
All 0s and 1 non zero cases

In [5]:
A = np.zeros(s)
for i in range(2):
    for j in range(2):
        test = A
        test[i][j] = 1
        det = np.linalg.det(test) 
        if det != -1:
            if det != 0:
                if det != 1:
                    print("False")

The 2 ones cases are checked above so now the all 1's and 3 1's cases

In [8]:
A = np.ones(s)
det = np.linalg.det(A) 
if det != -1:
    if det != 0:
        if det != 1:
            print("False")
for i in range(2):
    for j in range(2):
        test = A
        test[i][j] = 0
        det = np.linalg.det(test) 
        if det != -1:
            if det != 0:
                if det != 1:
                    print("False")